# Generated by Django 3.2 on 2021-08-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(default='kerala', max_length=50)),
                ('state', models.CharField(default='kereala', max_length=50)),
                ('country', models.CharField(default='india', max_length=50)),
                ('zip_code', models.CharField(default='pincode', max_length=12)),
                ('code', models.IntegerField(default=20)),
                ('mobile', models.IntegerField(default=1234567890)),
                ('email', models.EmailField(default='123@gmail.com', max_length=254)),
            ],
        ),
    ]
